{
 "title": "Apache Response Times",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Quickest response",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "serv_time",
       "id": "1",
       "inlineScript": "_value / 1000000.0",
       "meta": {},
       "settings": { "script": { "inline": "_value / 1000000.0" } },
       "type": "min"
      }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Avg response",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "serv_time",
       "id": "1",
       "inlineScript": "_value / 1000000.0",
       "meta": {},
       "settings": { "script": { "inline": "_value / 1000000.0" } },
       "type": "avg"
      }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Slowest response",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "serv_time",
       "id": "1",
       "inlineScript": "_value / 1000000.0",
       "meta": {},
       "settings": { "script": { "inline": "_value / 1000000.0" } },
       "type": "max"
      }
     ],
     "timeField": "@timestamp"
    }
   ]
  }
 ]
}